package fix

var MsgTypeMapping11 = map[string]string{
	"0": 	"Heartbeat",
	"1": 	"Test Request",
	"2": 	"Resend Request",
	"3": 	"Reject",
	"4": 	"Sequence Reset",
	"5": 	"Logout",
	"A": 	"Logon",
}

var MsgTypeMapping40 = map[string]string{
	"0": 	"Heartbeat",
	"1": 	"Test Request",
	"2": 	"Resend Request",
	"3": 	"Reject",
	"4": 	"Sequence Reset",
	"5": 	"Logout",
	"6": 	"Indication of Interest",
	"7": 	"Advertisement",
	"8": 	"Execution Report",
	"9": 	"Order Cancel Reject",
	"A": 	"Logon",
	"B": 	"News",
	"C": 	"Email",
	"D": 	"New Order - Single",
	"E": 	"New Order - List",
	"F": 	"Order Cancel Request",
	"G": 	"Order Cancel/Replace Request",
	"H": 	"Order Status Request",
	"J": 	"Allocation",
	"K": 	"List Cancel Request",
	"L": 	"List Execute",
	"M": 	"List Status Request",
	"N": 	"List Status",
	"P": 	"Allocation ACK",
	"Q": 	"Don't Know Trade",
	"R": 	"Quote Request",
	"S": 	"Quote",
}

var MsgTypeMapping41 = map[string]string{
	"0": 	"Heartbeat",
	"1": 	"Test Request",
	"2": 	"Resend Request",
	"3": 	"Reject",
	"4": 	"Sequence Reset",
	"5": 	"Logout",
	"6": 	"Indication of Interest",
	"7": 	"Advertisement",
	"8": 	"Execution Report",
	"9": 	"Order Cancel Reject",
	"A": 	"Logon",
	"B": 	"News",
	"C": 	"Email",
	"D": 	"New Order - Single",
	"E": 	"New Order - List",
	"F": 	"Order Cancel Request",
	"G": 	"Order Cancel/Replace Request",
	"H": 	"Order Status Request",
	"J": 	"Allocation",
	"K": 	"List Cancel Request",
	"L": 	"List Execute",
	"M": 	"List Status Request",
	"N": 	"List Status",
	"P": 	"Allocation ACK",
	"Q": 	"Don't Know Trade",
	"R": 	"Quote Request",
	"S": 	"Quote",
	"T": 	"Settlement Instructions",
}

var MsgTypeMapping42 = map[string]string{
	"0": 	"Heartbeat",
	"1": 	"Test Request",
	"2": 	"Resend Request",
	"3": 	"Reject",
	"4": 	"Sequence Reset",
	"5": 	"Logout",
	"6": 	"Indication of Interest",
	"7": 	"Advertisement",
	"8": 	"Execution Report",
	"9": 	"Order Cancel Reject",
	"a": 	"Quote Status Request",
	"A": 	"Logon",
	"b": 	"Quote Acknowledgement",
	"B": 	"News",
	"c": 	"Security Definition Request",
	"C": 	"Email",
	"d": 	"Security Definition",
	"D": 	"New Order - Single",
	"e": 	"Security Status Request",
	"E": 	"New Order - List",
	"f": 	"Security Status",
	"F": 	"Order Cancel Request",
	"g": 	"Trading Session Status Request",
	"G": 	"Order Cancel/Replace Request",
	"h": 	"Trading Session Status",
	"H": 	"Order Status Request",
	"i": 	"Mass Quote",
	"j": 	"Business Message Reject",
	"J": 	"Allocation",
	"k": 	"Bid Request",
	"K": 	"List Cancel Request",
	"l": 	"Bid Response",
	"L": 	"List Execute",
	"m": 	"List Strike Price",
	"M": 	"List Status Request",
	"N": 	"List Status",
	"P": 	"Allocation ACK",
	"Q": 	"Don't Know Trade",
	"R": 	"Quote Request",
	"S": 	"Quote",
	"T": 	"Settlement Instructions",
	"V": 	"Market Data Request",
	"W": 	"Market Data - Snapshot/Full Refresh",
	"X": 	"Market Data - Incremental Refresh",
	"Y": 	"Market Data Request Reject",
	"Z": 	"Quote Cancel",
}

var MsgTypeMapping43 = map[string]string{
	"0": 	"Heartbeat",
	"1": 	"Test Request",
	"2": 	"Resend Request",
	"3": 	"Reject",
	"4": 	"Sequence Reset",
	"5": 	"Logout",
	"6": 	"Indications of Interest",
	"7": 	"Advertisement",
	"8": 	"Execution Report",
	"9": 	"Order Cancel Reject",
	"a": 	"Quote Status Request",
	"A": 	"Logon",
	"AA": 	"Derivative Security List",
	"AB": 	"New Order - Multileg",
	"AC": 	"Multileg Order Cancel/Replace Request",
	"AD": 	"Trade Capture Report Request",
	"AE": 	"Trade Capture Report",
	"AF": 	"Order Mass Status Request",
	"AG": 	"Quote Request Reject",
	"AH": 	"RFQ Request",
	"AI": 	"Quote Status Report",
	"b": 	"Mass Quote Acknowledgement",
	"B": 	"News",
	"c": 	"Security Definition Request",
	"C": 	"Email",
	"d": 	"Security Definition",
	"D": 	"New Order - Single",
	"e": 	"Security Status Request",
	"E": 	"New Order - List",
	"f": 	"Security Status",
	"F": 	"Order Cancel Request",
	"g": 	"Trading Session Status Request",
	"G": 	"Order Cancel/Replace Request",
	"h": 	"Trading Session Status",
	"H": 	"Order Status Request",
	"i": 	"Mass Quote",
	"j": 	"Business Message Reject",
	"J": 	"Allocation",
	"k": 	"Bid Request",
	"K": 	"List Cancel Request",
	"l": 	"Bid Response",
	"L": 	"List Execute",
	"m": 	"List Strike Price",
	"M": 	"List Status Request",
	"n": 	"XML Message",
	"N": 	"List Status",
	"o": 	"Registration Instructions",
	"p": 	"Registration Instructions Response",
	"P": 	"Allocation ACK",
	"q": 	"Order Mass Cancel Request",
	"Q": 	"Don't Know Trade",
	"r": 	"Order Mass Cancel Report",
	"R": 	"Quote Request",
	"s": 	"New Order - Cross",
	"S": 	"Quote",
	"t": 	"Cross Order Cancel/Replace Request",
	"T": 	"Settlement Instructions",
	"u": 	"Cross Order Cancel Request",
	"v": 	"Security Type Request",
	"V": 	"Market Data Request",
	"w": 	"Security Types",
	"W": 	"Market Data - Snapshot/Full Refresh",
	"x": 	"Security List Request",
	"X": 	"Market Data - Incremental Refresh",
	"y": 	"Security List",
	"Y": 	"Market Data Request Reject",
	"z": 	"Derivative Security List Request",
	"Z": 	"Quote Cancel",
}

var MsgTypeMapping44 = map[string]string{
	"0": 	"Heartbeat",
	"1": 	"Test Request",
	"2": 	"Resend Request",
	"3": 	"Reject",
	"4": 	"Sequence Reset",
	"5": 	"Logout",
	"6": 	"IOI",
	"7": 	"Advertisement",
	"8": 	"Execution Report",
	"9": 	"Order Cancel Reject",
	"a": 	"Quote Status Request",
	"A": 	"Logon",
	"AA": 	"Derivative Security List",
	"AB": 	"New Order Multileg",
	"AC": 	"Multileg Order Cancel/Replace",
	"AD": 	"Trade Capture Report Request",
	"AE": 	"Trade Capture Report",
	"AF": 	"Order Mass Status Request",
	"AG": 	"Quote Request Reject",
	"AH": 	"RFQ Request",
	"AI": 	"Quote Status Report",
	"AJ": 	"Quote Response",
	"AK": 	"Confirmation",
	"AL": 	"Position Maintenance Request",
	"AM": 	"Position Maintenance Report",
	"AN": 	"Request For Positions",
	"AO": 	"Request for Positions Ack",
	"AP": 	"Position Report",
	"AQ": 	"Trade Capture Report Request Ack",
	"AR": 	"Trade Capture Report Ack",
	"AS": 	"Allocation Report",
	"AT": 	"Allocation Report Ack",
	"AU": 	"Confirmation Ack",
	"AV": 	"Settlement Instruction Request",
	"AW": 	"Assignment Report",
	"AX": 	"Collateral Request",
	"AY": 	"Collateral Assignment",
	"AZ": 	"Collateral Response",
	"b": 	"Mass Quote Acknowledgement",
	"B": 	"News",
	"BA": 	"Collateral Report",
	"BB": 	"Collateral Inquiry",
	"BC": 	"Network Counterparty System Status Request",
	"BD": 	"Network Counterparty System Status Response",
	"BE": 	"User Request",
	"BF": 	"User Response",
	"BG": 	"Collateral Inquiry Ack",
	"BH": 	"Confirmation Request",
	"c": 	"Security Definition Request",
	"C": 	"Email",
	"d": 	"Security Definition",
	"D": 	"New Order Single",
	"e": 	"Security Status Request",
	"E": 	"New Order List",
	"f": 	"Security Status",
	"F": 	"Order Cancel Request",
	"g": 	"Trading Session Status Request",
	"G": 	"Order Cancel/Replace Request",
	"h": 	"Trading Session Status",
	"H": 	"Order Status Request",
	"i": 	"Mass Quote",
	"j": 	"Business Message Reject",
	"J": 	"Allocation Instruction",
	"k": 	"Bid Request",
	"K": 	"List Cancel Request",
	"l": 	"Bid Response",
	"L": 	"List Execute",
	"m": 	"List Strike Price",
	"M": 	"List Status Request",
	"n": 	"XML Message",
	"N": 	"List Status",
	"o": 	"Registration Instructions",
	"p": 	"Registration Instructions Response",
	"P": 	"Allocation Instruction Ack",
	"q": 	"Order Mass Cancel Request",
	"Q": 	"Don't Know Trade",
	"r": 	"Order Mass Cancel Report",
	"R": 	"Quote Request",
	"s": 	"New Order Cross",
	"S": 	"Quote",
	"t": 	"Cross Order Cancel/Replace Request",
	"T": 	"Settlement Instructions",
	"u": 	"Cross Order Cancel Request",
	"v": 	"Security Type Request",
	"V": 	"Market Data Request",
	"w": 	"Security Types",
	"W": 	"Market Data - Snapshot/Full Refresh",
	"x": 	"Security List Request",
	"X": 	"Market Data - Incremental Refresh",
	"y": 	"Security List",
	"Y": 	"Market Data Request Reject",
	"z": 	"Derivative Security List Request",
	"Z": 	"Quote Cancel",
}

var MsgTypeMapping50 = map[string]string{
	"0": 	"Heartbeat",
	"1": 	"TestRequest",
	"2": 	"ResendRequest",
	"3": 	"Reject",
	"4": 	"SequenceReset",
	"5": 	"Logout",
	"6": 	"IOI",
	"7": 	"Advertisement",
	"8": 	"ExecutionReport",
	"9": 	"OrderCancelReject",
	"a": 	"QuoteStatusRequest",
	"A": 	"Logon",
	"AA": 	"DerivativeSecurityList",
	"AB": 	"NewOrderMultileg",
	"AC": 	"MultilegOrderCancelReplace",
	"AD": 	"TradeCaptureReportRequest",
	"AE": 	"TradeCaptureReport",
	"AF": 	"OrderMassStatusRequest",
	"AG": 	"QuoteRequestReject",
	"AH": 	"RFQRequest",
	"AI": 	"QuoteStatusReport",
	"AJ": 	"QuoteResponse",
	"AK": 	"Confirmation",
	"AL": 	"PositionMaintenanceRequest",
	"AM": 	"PositionMaintenanceReport",
	"AN": 	"RequestForPositions",
	"AO": 	"RequestForPositionsAck",
	"AP": 	"PositionReport",
	"AQ": 	"TradeCaptureReportRequestAck",
	"AR": 	"TradeCaptureReportAck",
	"AS": 	"AllocationReport",
	"AT": 	"AllocationReportAck",
	"AU": 	"Confirmation_Ack",
	"AV": 	"SettlementInstructionRequest",
	"AW": 	"AssignmentReport",
	"AX": 	"CollateralRequest",
	"AY": 	"CollateralAssignment",
	"AZ": 	"CollateralResponse",
	"b": 	"MassQuoteAcknowledgement",
	"B": 	"News",
	"BA": 	"CollateralReport",
	"BB": 	"CollateralInquiry",
	"BC": 	"NetworkCounterpartySystemStatusRequest",
	"BD": 	"NetworkCounterpartySystemStatusResponse",
	"BE": 	"UserRequest",
	"BF": 	"UserResponse",
	"BG": 	"CollateralInquiryAck",
	"BH": 	"ConfirmationRequest",
	"BI": 	"TradingSessionListRequest",
	"BJ": 	"TradingSessionList",
	"BK": 	"SecurityListUpdateReport",
	"BL": 	"AdjustedPositionReport",
	"BM": 	"AllocationInstructionAlert",
	"BN": 	"ExecutionAcknowledgement",
	"BO": 	"ContraryIntentionReport",
	"BP": 	"SecurityDefinitionUpdateReport",
	"c": 	"SecurityDefinitionRequest",
	"C": 	"Email",
	"d": 	"SecurityDefinition",
	"D": 	"NewOrderSingle",
	"e": 	"SecurityStatusRequest",
	"E": 	"NewOrderList",
	"f": 	"SecurityStatus",
	"F": 	"OrderCancelRequest",
	"g": 	"TradingSessionStatusRequest",
	"G": 	"OrderCancelReplaceRequest",
	"h": 	"TradingSessionStatus",
	"H": 	"OrderStatusRequest",
	"i": 	"MassQuote",
	"j": 	"BusinessMessageReject",
	"J": 	"AllocationInstruction",
	"k": 	"BidRequest",
	"K": 	"ListCancelRequest",
	"l": 	"BidResponse",
	"L": 	"ListExecute",
	"m": 	"ListStrikePrice",
	"M": 	"ListStatusRequest",
	"n": 	"XML_non_FIX",
	"N": 	"ListStatus",
	"o": 	"RegistrationInstructions",
	"p": 	"RegistrationInstructionsResponse",
	"P": 	"AllocationInstructionAck",
	"q": 	"OrderMassCancelRequest",
	"Q": 	"DontKnowTradeDK",
	"r": 	"OrderMassCancelReport",
	"R": 	"QuoteRequest",
	"s": 	"NewOrderCross",
	"S": 	"Quote",
	"t": 	"CrossOrderCancelReplaceRequest",
	"T": 	"SettlementInstructions",
	"u": 	"CrossOrderCancelRequest",
	"v": 	"SecurityTypeRequest",
	"V": 	"MarketDataRequest",
	"w": 	"SecurityTypes",
	"W": 	"MarketDataSnapshotFullRefresh",
	"x": 	"SecurityListRequest",
	"X": 	"MarketDataIncrementalRefresh",
	"y": 	"SecurityList",
	"Y": 	"MarketDataRequestReject",
	"z": 	"DerivativeSecurityListRequest",
	"Z": 	"QuoteCancel",
}
